server:
  port: 8080

spring:
  datasource:
    username: root
    password: qwerty
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSl=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

indexing-settings:
  sites:
    - url: https://nikoartgallery.com/
      name: NIKO
#    - url: https://www.svetlovka.ru/
#      name: SVETLOVKA
#    - url: https://redcom.ru/
#      name: REDCOM
  frequency-threshold: 0.5
  snippet-length-max: 30

connection-humanizer:
  user-agent: FerritSearchBot
  referrer: http://www.google.com
  sleep-length:
    minimum: 500
    maximum: 600